apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-chown-data
        image: busybox:1.28
        command: ["sh", "-c", "mkdir -p /data/loki/chunks /data/loki/index /data/loki/wal && chown -R 10001:10001 /data"]
        volumeMounts:
        - name: storage
          mountPath: /data
      containers:
      - name: loki
        image: grafana/loki:2.4.0
        ports:
        - containerPort: 3100
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: config
          mountPath: /etc/loki/local-config.yaml
          subPath: loki.yaml
        - name: storage
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        persistentVolumeClaim:
          claimName: loki-storage
