apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: grafana-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.23.1
        args:
        - "query"
        - "--http-address=0.0.0.0:10902"
        - "--store=thanos-sidecar.grafana-ha.svc.cluster.local:10901"
        ports:
        - containerPort: 10902
