apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: grafana-ha
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "thanos"
      endpoint: "minio:9000"
      access_key: "minio"
      secret_key: "minio123"
      insecure: true
